### ISSUE TITLE
Discovery problem

### ISSUE THREAD

**Issue by srekkas** [limpapud/zabbix_templates#3]
Hello, 

  I tested template on two NVR's and discovery wont work. Get this error
snmp_parse_oid(): cannot parse OID "HIKVISION-MIB::hikDiskIndex".

> [root@zabbix mibs]# snmpwalk -c public -v 2c x.x.x.x 1.3.6.1.4.1
HIKVISION-MIB::hikIp.0 = Network Address: 0A:14:50:28
HIKVISION-MIB::hikPort.0 = INTEGER: 8000
HIKVISION-MIB::hikEntityIndex.0 = STRING: 1620171214CCRRC01965385WCVU
HIKVISION-MIB::hikEntityType.0 = INTEGER: dvr(1)
HIKVISION-MIB::hikEntitySubType.0 = INTEGER: dvr-71xx(2)
HIKVISION-MIB::hikOnline.0 = INTEGER: online(1)
HIKVISION-MIB::hikService.0 = INTEGER: unknown(255)
HIKVISION-MIB::hikCMSDefType.0 = INTEGER: unknown(255)
HIKVISION-MIB::hikObjectID.0 = INTEGER: 0
HIKVISION-MIB::hikObjectName.0 = STRING:
HIKVISION-MIB::hikTrapHostIp1.0 = STRING:
HIKVISION-MIB::hikCPUNum.0 = INTEGER: 1
HIKVISION-MIB::hikCPUFrequency.0 = STRING: 1000MHZ
HIKVISION-MIB::hikMemoryCapability.0 = INTEGER: 500
HIKVISION-MIB::hikMemoryUsage.0 = INTEGER: 5
HIKVISION-MIB::hikDeviceStatus.0 = INTEGER: online(1)
HIKVISION-MIB::hikDeviceLanguage.0 = INTEGER: 6
HIKVISION-MIB::hikDiskNum.0 = INTEGER: 2
HIKVISION-MIB::hikDiskIndex.1.0 = INTEGER: 1
HIKVISION-MIB::hikDiskIndex.2.0 = INTEGER: 2
HIKVISION-MIB::hikDiskVolume.1.0 = STRING: lable01
HIKVISION-MIB::hikDiskVolume.2.0 = STRING: lable02
HIKVISION-MIB::hikDiskStatus.1.0 = INTEGER: normal(0)
HIKVISION-MIB::hikDiskStatus.2.0 = INTEGER: normal(0)
HIKVISION-MIB::hikDiskFreeSpace.1.0 = INTEGER: 0
HIKVISION-MIB::hikDiskFreeSpace.2.0 = INTEGER: 0
HIKVISION-MIB::hikDiskCapability.1.0 = INTEGER: 5723166
HIKVISION-MIB::hikDiskCapability.2.0 = INTEGER: 5723166
HIKVISION-MIB::hikDiskCapability.2.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
You have mail in /var/spool/mail/root

**Comment by srekkas** [comment]
OK, i needed to restart Zabbix-server to get MIB, and restarted snmpd too
everything seems ok

**Comment by ahaddouche** [comment]
In my case the discovery wont work.

[root@zabbix ~]# snmpwalk -v 2c -c snmpBnde14 172.17.5.17 1.3.6.1.4.1
SNMPv2-SMI::enterprises.50001.1.1.0 = IpAddress: 172.17.6.100
SNMPv2-SMI::enterprises.50001.1.2.0 = INTEGER: 8000
SNMPv2-SMI::enterprises.50001.1.3.0 = STRING: "1620190628CCRRD35408318WCVU"
SNMPv2-SMI::enterprises.50001.1.100.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.101.0 = INTEGER: 2
SNMPv2-SMI::enterprises.50001.1.102.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.103.0 = INTEGER: 255
SNMPv2-SMI::enterprises.50001.1.104.0 = INTEGER: 255
SNMPv2-SMI::enterprises.50001.1.105.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.106.0 = ""
SNMPv2-SMI::enterprises.50001.1.110.0 = STRING: "172.17.11.124"
SNMPv2-SMI::enterprises.50001.1.200.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.201.0 = STRING: "1000MHZ"
SNMPv2-SMI::enterprises.50001.1.220.0 = INTEGER: 1515
SNMPv2-SMI::enterprises.50001.1.221.0 = INTEGER: 2
SNMPv2-SMI::enterprises.50001.1.230.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.231.0 = INTEGER: 6
SNMPv2-SMI::enterprises.50001.1.240.0 = INTEGER: 4
SNMPv2-SMI::enterprises.50001.1.241.1.1.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.241.1.1.2.0 = INTEGER: 2
SNMPv2-SMI::enterprises.50001.1.241.1.1.3.0 = INTEGER: 3
SNMPv2-SMI::enterprises.50001.1.241.1.1.4.0 = INTEGER: 4
SNMPv2-SMI::enterprises.50001.1.241.1.2.1.0 = STRING: "lable01"
SNMPv2-SMI::enterprises.50001.1.241.1.2.2.0 = STRING: "lable02"
SNMPv2-SMI::enterprises.50001.1.241.1.2.3.0 = STRING: "lable03"
SNMPv2-SMI::enterprises.50001.1.241.1.2.4.0 = STRING: "lable04"
SNMPv2-SMI::enterprises.50001.1.241.1.3.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.3.2.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.3.3.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.3.4.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.2.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.3.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.4.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.5.1.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.2.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.3.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.4.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by ahaddouche** [comment]
Hello;

In my case the discovery wont work.

[root@zabbix ~]# snmpwalk -v 2c -c public xx.xx.xx.xx 1.3.6.1.4.1
SNMPv2-SMI::enterprises.50001.1.1.0 = IpAddress: xx.xx.xx.xx
SNMPv2-SMI::enterprises.50001.1.2.0 = INTEGER: 8000
SNMPv2-SMI::enterprises.50001.1.3.0 = STRING: "1620190628CCRRD35408318WCVU"
SNMPv2-SMI::enterprises.50001.1.100.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.101.0 = INTEGER: 2
SNMPv2-SMI::enterprises.50001.1.102.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.103.0 = INTEGER: 255
SNMPv2-SMI::enterprises.50001.1.104.0 = INTEGER: 255
SNMPv2-SMI::enterprises.50001.1.105.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.106.0 = ""
SNMPv2-SMI::enterprises.50001.1.110.0 = STRING: "xx.xx.xx.xx"
SNMPv2-SMI::enterprises.50001.1.200.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.201.0 = STRING: "1000MHZ"
SNMPv2-SMI::enterprises.50001.1.220.0 = INTEGER: 1515
SNMPv2-SMI::enterprises.50001.1.221.0 = INTEGER: 2
SNMPv2-SMI::enterprises.50001.1.230.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.231.0 = INTEGER: 6
SNMPv2-SMI::enterprises.50001.1.240.0 = INTEGER: 4
SNMPv2-SMI::enterprises.50001.1.241.1.1.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.50001.1.241.1.1.2.0 = INTEGER: 2
SNMPv2-SMI::enterprises.50001.1.241.1.1.3.0 = INTEGER: 3
SNMPv2-SMI::enterprises.50001.1.241.1.1.4.0 = INTEGER: 4
SNMPv2-SMI::enterprises.50001.1.241.1.2.1.0 = STRING: "lable01"
SNMPv2-SMI::enterprises.50001.1.241.1.2.2.0 = STRING: "lable02"
SNMPv2-SMI::enterprises.50001.1.241.1.2.3.0 = STRING: "lable03"
SNMPv2-SMI::enterprises.50001.1.241.1.2.4.0 = STRING: "lable04"
SNMPv2-SMI::enterprises.50001.1.241.1.3.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.3.2.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.3.3.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.3.4.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.2.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.3.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.4.4.0 = INTEGER: 0
SNMPv2-SMI::enterprises.50001.1.241.1.5.1.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.2.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.3.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.4.0 = INTEGER: 3815447
SNMPv2-SMI::enterprises.50001.1.241.1.5.4.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
